# Generated by Django 5.2.8 on 2025-12-14 04:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 0, 57, 704009, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 0, 57, 704009, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 0, 57, 704009, tzinfo=datetime.timezone.utc))),
                ('total_amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 0, 57, 704009, tzinfo=datetime.timezone.utc))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pos.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(default=0)),
                ('cost_price', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 0, 57, 704009, tzinfo=datetime.timezone.utc))),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pos.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 0, 57, 704009, tzinfo=datetime.timezone.utc))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pos.product')),
            ],
        ),
    ]
