# Generated by Django 5.2.8 on 2026-01-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
